<?php

namespace Application\Entity;

/**
 * TipoInvestimentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoInvestimentoRepository extends \Doctrine\ORM\EntityRepository
{

    public function listarTipos($dataInicial, $dataFinal){

        return $this->createQueryBuilder('tipo')
            ->andWhere('tipo.dataCadastro BETWEEN :dataInicial AND :dataFinal')
            ->setParameters(array(
                'dataInicial' => $dataInicial->format('Y-m-d'),
                'dataFinal' => $dataFinal->format('Y-m-d')
            ))
            ->getQuery()
            ->execute();
    }
}
