<?php
if($this->success)
    echo '<div class="alert alert-success" role="alert">'.$this->success[0].'
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          </div>';
elseif($this->error)
    echo '<div class="alert alert-danger" role="alert">'.$this->error[0].'
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          </div>';
elseif($this->warning)
    echo '<div class="alert alert-info" role="alert">'.$this->warning[0].'
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          </div>';
?>
<div class="col-md-12 row" style="margin:15px 0px">
    <div class="pull-right">
        <a href="<?= $this->url('tipo-investimento', array('controller' => '', 'action' => 'inserir'))?>">
            <button type="button" class="btn btn-default">Novo Registro</button>
        </a>
    </div>
</div>
<div class="col-md-12">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Tipos de Investimento</h3>
        </div>
        <div class="panel-body">

            <?php

            /**
             * @var $form \Zend\Form\Form
             */
            $form = $this->form;

            $this->formElementErrors()
                ->setMessageOpenFormat('<div class="alert alert-danger alert-dismissible" role="alert">
                                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                  </button>')
                ->setMessageCloseString('</div>')
                ->render($form);
            $form->setAttribute('action', $this->url('tipo-investimento', array('controller' => '', 'action' => 'index')));

            $form->prepare();

            echo $this->form($form, TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_INLINE);
            ?>
            <div class="col-md-12" style="margin-top:20px;">
                <table class="table table-condensed table-hover table-striped">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Nome</th>
                            <th>Rentabilidade</th>
                            <th>Taxa</th>
                            <th>Período da Aplicação</th>
                            <th>Data de Cadastro</th>
                            <th>Opções</th>
                        </tr>
                    </thead>

                    <?php
                        /**
                         * @var $tipoInvestimento \Application\Entity\TipoInvestimento
                         */
                    ?>

                    <tbody>
                        <?php if($this->data): ?>
                            <?php foreach ($this->data as $tipoInvestimento): ?>
                            <tr>
                                <td><?= $tipoInvestimento->getId()?></td>
                                <td><?= $tipoInvestimento->getDescricao()?></td>
                                <td><?= $tipoInvestimento->getRentabilidade()?> %</td>
                                <td><?= $tipoInvestimento->getTaxa()?> %</td>
                                <td><?= $tipoInvestimento->getPeriodoAplicacao()?> Dias</td>
                                <td><?= $tipoInvestimento->getDataCadastro()->format('d/m/Y')?></td>
                                <td>
                                    <a href="<?= $this->url('tipo-investimento', array('controller' => '', 'action' => 'editar', 'id' => $tipoInvestimento->getId()))?>">
                                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                                    </a>
                                    <a href="javascript://" class="excluir-registro" data-id="<?= $tipoInvestimento->getId()?>">
                                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                    </a>
                                </td>
                            </tr>
                            <?php endforeach;?>
                        <?php endif;?>
                    </tbody>
                </table>
                <?= $this->paginationControl($this->data, 'Sliding', 'partials/paginator', array('route' => 'tipo-investimento/paginator'))?>
            </div>
        </div>
    </div>
</div>

<script>
    $(function(){
        $('.excluir-registro').bind('click', function () {
            var idRegistro = $(this).data().id;
            bootbox.confirm({
                message: "Deseja remover este registro?",
                title: "Remover",
                callback: function (result) {
                    if(result)
                        window.location.href = '<?= $this->url('tipo-investimento', array('controller' => '', 'action' => 'excluir'))?>/'+idRegistro;
                }
            });
        });
        $('#data_inicial').mask('00/00/0000');
        $('#data_final').mask('00/00/0000');
    });
</script>