<?php
    $urlPattern = $_SERVER['REQUEST_URI'];
    $formatUrl = function($page) use($urlPattern){
        $queryParamPos = stripos($urlPattern, '?');
        $queryParam = '';
        if($queryParamPos !== false) {
            $queryParam = substr($urlPattern, $queryParamPos);
            $urlPattern = substr($urlPattern, 0, $queryParamPos);
        }

        if(!preg_match('/page/', $urlPattern)) {
            if(substr($urlPattern, -1) == '/')
                return $urlPattern . 'page/' . (int)$page.$queryParam;
            else
                return $urlPattern . '/page/' . (int)$page.$queryParam;
        }else
            if(substr($urlPattern, -1) == '/')
                return preg_replace('@page/(\d+)@', 'page/'.(int)$page, $urlPattern).$queryParam;
            else
                return preg_replace('@/page/(\d+)@', '/page/'.(int)$page, $urlPattern).$queryParam;
    }
?>

<?php if ($this->pageCount): ?>
    <div>
        <ul class="pagination">
            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <li>
                    <a href="<?= $formatUrl($this->previous)?>">
                        <<
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        <<
                    </a>
                </li>
            <?php endif; ?>

            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li>
                        <a href="<?= $formatUrl($page)?>">
                            <?php echo $page; ?>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="active">
                        <a href="#"><?php echo $page; ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li>
                    <a href="<?= $formatUrl($this->next)?>">
                        >>
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        >>
                    </a>
                </li>
            <?php endif; ?>
        </ul>
    </div>
<?php endif; ?>