<div class="row">
<?php
if($this->success)
    echo '<div class="alert alert-success" role="alert">'.$this->success[0].'</div>';
elseif($this->error)
    echo '<div class="alert alert-danger" role="alert">'.$this->error[0].'</div>';
elseif($this->warning)
    echo '<div class="alert alert-info" role="alert">'.$this->warning[0].'</div>';
?>

<h2>Novo tipo de investimento financeiro.</h2>

<?php

/**
 * @var $form \Zend\Form\Form
 */
    $form = $this->form;

    $this->formElementErrors()
        ->setMessageOpenFormat('<div class="alert alert-danger alert-dismissible" role="alert">
                                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                  </button>')
        ->setMessageCloseString('</div>')
        ->render($form);



    $form->prepare();
    echo '<div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">Tipos de Investimento</h3>
              </div>
              <div class="panel-body">
                  <div class="col-md-12">';
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();
    echo '        </div>
              </div>
          </div>';
?>
</div>

<script>
    $(function(){
        $('#data').mask('00/00/0000', {placeholder: "__/__/____"});
        $('#aplicacao').mask('000.000.000.000.000,00', {reverse: true});
    });
</script>
